"""Add is_pinned to conversations

Revision ID: 407d88e95363
Revises: dc0f5c0d0968
Create Date: 2026-08-01 17:46:50.009715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407d88e95363'
down_revision = 'dc0f5c0d0968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
