"""add cascade deletes to conversation children

Revision ID: 86b9075e3dc0
Revises: 407d88e95363
Create Date: 2026-09-10 20:29:34.213756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b9075e3dc0'
down_revision = '407d88e95363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pdfs_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pdfs_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###
