"""Update PDF schema

Revision ID: dc0f5c0d0968
Revises: 82b57c78c7c6
Create Date: 2026-07-28 05:21:35.124516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0f5c0d0968'
down_revision = '82b57c78c7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pdfs_file_size_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('pdfs_original_filename_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('pdfs_original_filename_key'), ['original_filename'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('pdfs_file_size_key'), ['file_size'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
